### ISSUE TITLE
Use Lighthouse or similar tool to profile freenet.org page load and identify bottlenecks

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#369]
- [ ] Inline JS/CSS
 - [ ] Update JQuery due to vulnerability, or remove? Does Bulma need JQuery?
 - [ ] Various service-worker issues in PWA section

**Comment by sanity** [comment]
One or two of the points are specific to freenet.org but most of these improvements will benefit kweb overall, so I think this is the right place for it.

**Comment by sanity** [comment]
> Was this supposed to be in the freenetorg-website repo?

No, it's to optimize Kweb generally.
